### ISSUE TITLE
☂️ go-perun [pkg] migration

### ISSUE THREAD

**Issue by ggwpez** [perun-network/poly-go#8]
- [x] Copy the commits and content from `[pkg]` (#10)
- [x] Move all files from `./pkg/` to `./`
- [x] Update the vanity import paths
- [x] Update the imports
- [x] Create go.(mod|sum)
- [x] Create NOTICE (#11)
- [ ] Fixup all comments
- [ ] Add README (#9)
- [x] Add Github CI (#3, #11)
- [x] Change license header in each source file to the [shorter SPDX version](https://spdx.dev/ids/#how) (#11):
```
// SPDX-License-Identifier: Apache-2.0
```
- [x] Serve vanity import path on `polycry.pt/poly-go` (#1)

**Comment by sebastianst** [comment]
- [ ] Add Github CI Action
- [ ] Change license header in each source file to the [shorter SPDX version](https://spdx.dev/ids/#how):
```
// SPDX-License-Identifier: Apache-2.0
```
